#!/bin/sh
# wrapper around playerctl that automatically detects current player
ignorelist=The_Jacket_H2O_3
player=
altplayer=
for p in $(playerctl -l); do
    status="$(playerctl -p "$p" status)"
    if [ "$status" = Playing ]; then
        player="$p"
        break
    elif [ "$status" != Stopped -a -z "$altplayer" ]; then
        altplayer="$p"
    fi
done

if [ "$player" -o "$altplayer" ]; then
    playerctl -p "${player:-$altplayer}" $@
else
    >&2 echo "No active player found"
    playerctl -i "$ignorelist" $@
fi
