#!/usr/bin/env bash
usage(){
    _filename=${0##*/}
    echo "Usage: $_filename ([#]HEX|R G B)"
    echo "       where HEX is 6 or 3 digit hex number, and R G B are 3 integers between 0 and 255"
    echo
    echo "Examples:"
    echo "  $_filename ef2322              # out: 'rgb(239, 35, 34)'"
    echo "  $_filename '#566543'           # out: 'rgb(86, 101, 67)'"
    echo "  $_filename 233 34 12           # out: '#e9220c'"
}

if [ $# -eq 1 ]; then
    _hex=$1
    
    # trim trailing # if present
    [ ${_hex:0:1} == "#" ] && _hex=${_hex#\#}

    # hex value should be either 6 or 3 chars long
    if [[ ! (${#_hex} -eq 6 || ${#_hex} -eq 3) ]]; then
        1>&2 echo "ERROR: hex color should be 6 or 3 characters long"
        exit 1
    fi

    if [ ${#_hex} -eq 6 ]; then
        printf "rgb(%d, %d, %d)" "0x${_hex:0:2}" "0x${_hex:2:2}" "0x${_hex:4:2}"
    else 
        _r=${_hex:0:1}
        _g=${_hex:1:1}
        _b=${_hex:2:1}
        printf "rgb(%d, %d, %d)" "0x$_r$_r" "0x$_g$_g" "0x$_b$_b" 
    fi
    echo
elif [ $# -eq 3 ]; then
    _r=$1
    _g=$2
    _b=$3

    if [[ ! ( ( $_r -ge 0 && $_r -le 255 && $_g -ge 0 && $_g -le 255 && $_b -ge 0 && $_b -le 255 ) ) ]]; then
        1>&2 echo "ERROR: invalid rgb values, each number must be between 0 and 255"
        exit 1
    else
        printf "#%02x%02x%02x" "$_r" "$_g" "$_b" 
    fi
    echo
else
    usage
fi

