#!/bin/sh

# dahua servers folder
conf="${XDG_CONFIG_HOME:-$HOME/.config}/dahua.conf"
fifo="${XDG_CACHE_HOME:-$HOME/.cache}/dahua.fifo"

die() {
	if [ -t 0 ]; then
		>&2 echo "$@"
	else
		notify-send -u low "dahua" "$*"
	fi

	exit 1
}

while getopts "c" o; do case "$o" in
    h) die "Usage: dahua [-c CONF]" ;;
    c) conf="$OPTARG" ;;
    *) die "Invalid option; -$o" ;;
esac done

if ! command -v mpv >/dev/null; then
	die "mpv not found"
elif [ ! -r "$conf" ]; then
	die "Configuration not found: $conf"
fi

source "$conf"

channelname=$(echo $channels | tr ";" "\n" | cut -d: -f1 | dmenu -i -p "Choose a channel:")
channel=$(echo $channels | tr ";" "\n" | grep -F "$channelname" | cut -d: -f2)
stream="rtsp://${user:-admin}:${pass:-admin}@$host:${port:-554}/cam/realmonitor?channel=$channel&subtype=0"

exec mpv --aid=no --title="Camera: $channelname" "$stream"
