#!/bin/sh

# USAGE: ./github-rpm OWNER/REPO
# Get the latest rpm from the releases of the repo

if ! command -v gh >/dev/null; then
    >&2 echo "Error: github-cli not found"
    exit 1
fi

repo="$1"
version="$(gh release list -R "$repo" | grep Latest | awk '{print $1}')"
mach="$(uname -m)"
gh release view \
    --json assets \
    --jq ".assets[] | select( .name | contains(\"$mach.rpm\")) | .url" \
    "$version" \
    -R "$repo"
