#!/bin/sh

_opt=$(echo "logout\nsuspend\nhibernate\nreboot\npoweroff" | dmenu -p "Power Menu: ")

if [ $_opt ]; then
    _sel=$(echo -n $_opt | tr "[:lower:]" "[:upper:]")
    _sure=$(echo -n "no\nyes" | dmenu -p "$_sel. Proceed? ")

    [ "$_sure" != "yes" ] && exit 0

    if [ "$_opt" = "logout" ]; then
        i3-msg exit
    else
        systemctl "$_opt"
    fi
else 
    errcho -e "No option selected"
fi

