#!/bin/sh

# custom search engines using dmenu

# config is a SSV (space separated value) file with 2 columns:
# name: to be shown in dmenu
# url_template: used by printf to replace the query
#
# url_template must contain 1 instance of the string '%s' to be replaced by printf
config="${XDG_CONFIG_HOME:-$HOME/.config}/searchengines"
if [ -f "$config" ]; then 
	engine=$(cut -d' ' -f1 "$config" | dmenu -p "Search engine:" -it "ddg")
fi

if [ "$engine" ]; then
	if [ "$engine" = ddg ]; then
		url="https://duckduckgo.org/?q=%s"
	else
		url="$(grep "^$engine" "$config" | cut -d' ' -f2)"
	fi

	searchterm="$(dmenu -p "Search:" </dev/null | tr -d '\n' | jq -rRs @uri)"

	if [ -n "$searchterm" ]; then
		exec xdg-open "$(printf "$url" "$searchterm")"
	fi
fi
