import:
  - ~/.config/alacritty/custom_pre.yml

env:
  TERM: xterm-256color
window:
  dimensions:
    columns: 100
    lines: 28
  dynamic_padding: true

scrolling:
  multiplier: 5

cursor:
  vi_mode_style: Block

draw_bold_text_with_bright_colors: false

hints:
  enabled:
    - regex: "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)\
              [^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
      command: xdg-open
      post_processing: true
      binding:
        key: U
        mods: Control|Shift
    - regex: "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)\
              [^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
      action: Copy
      post_processing: true
      binding:
        key: Y
        mods: Control|Shift
