# no X server => we're probably sshing
if ! xset q &>/dev/null; then
	source ~/.profile
fi

# shut up
unsetopt beep
# for gitbranch on prompt
setopt prompt_subst
# zsh history
setopt appendhistory

# enable ./ ../ completion
zstyle ':completion:*' special-dirs true
zstyle ':completion:*' completer _expand _complete
# find new executables in PATH after installation
zstyle ':completion:*' rehash true
eval $(dircolors)
zstyle ':completion:*' list-colors $LS_COLORS

# awesome completion
autoload -Uz compinit
zle -N compinit
compinit

# edit command in vim
autoload -z edit-command-line
zle -N edit-command-line

# run when zsh vi mode is changed shows different indicators for each mode
zle-keymap-select() {
	case $KEYMAP in
		vicmd)      echo -ne "\e[2 q";; # block cursor
		viins|main) echo -ne "\e[6 q";; # pipe cursor
	esac
}
zle -N zle-keymap-select

# default to insert mode on start
zle-line-init() {
	zle -K viins
	echo -ne "\e[6 q"
}
zle -N zle-line-init

# start only one ssh-agent
agent_env="$XDG_RUNTIME_DIR/ssh-agent.env"
if ! pgrep -u "$USER" ssh-agent > /dev/null && [ -w "$agent_env" ]; then
  ssh-agent > "$agent_env"
fi
if [ ! "$SSH_AUTH_SOCK" -a -r "$agent_env" ]; then
  eval "$(<"$agent_env")" > /dev/null
fi

# z to jump between directories (with zoxide)
if command -v zoxide >/dev/null; then
	eval "$(zoxide init zsh)"
fi

# for aliases
[ -f "$ZDOTDIR"/zshaliases ] && source "$ZDOTDIR"/zshaliases

# for functions
[ -f "$ZDOTDIR"/zshfunctions ] && source "$ZDOTDIR"/zshfunctions

# for key bindings
[ -f "$ZDOTDIR"/zshkeybinds ] && source "$ZDOTDIR"/zshkeybinds

plugdir="/usr/share/zsh/plugins"
plugins=("zsh-autosuggestions/zsh-autosuggestions.plugin.zsh"
	       "fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh")

for p in $plugins; do
	[ -f "$plugdir/$p" ] && source "$plugdir/$p"
done
