#!/bin/sh

# Example for $XDG_CONFIG_HOME/sxiv/exec/key-handler
# Called by sxiv(1) after the external prefix key (C-x by default) is pressed.
# The next key combo is passed as its first argument. Passed via stdin are the
# images to act upon, one path per line: all marked images, if in thumbnail
# mode and at least one image has been marked, otherwise the current image.
# sxiv(1) blocks until this script terminates. It then checks which images
# have been modified and reloads them.

# The key combo argument has the following form: "[C-][M-][S-]KEY",
# where C/M/S indicate Ctrl/Meta(Alt)/Shift modifier states and KEY is the X
# keysym as listed in /usr/include/X11/keysymdef.h without the "XK_" prefix.

rotate() {
	degree="$1"
	tr '\n' '\0' | xargs -0 realpath | sort | uniq | while read file; do
	# use imagemagick
	convert "$file" -rotate $degree "$file"
	done
}

# usage: prompt PROMPT [DMENU_OPTION, ...]
prompt() {
	# get window id
	local wid="0x$( (echo 'obase=16;' ; xdotool getwindowfocus) | bc )"
	local prompt="$1"
	shift 1
	dmenu -W "$wid" -vp 0 -hp 0 -p "$prompt" $* </dev/null
}

case "$1" in
	# copy list of paths
	"Y")  xclip -in -selection clipboard ;;
	# copy first image to clipboard
	"y")  head -1 | xclip -selection clipboard -target image/png "$(cat -)" ;;
	# set first image as wallpaper
	"s")
		wall="${XDG_DATA_HOME:-$HOME/.local/share}/wallpaper" 
		head -1 | ln -fs "$(cat -)" "$wall" && bgs -z "$wall" ;;
	# rotate clockwise all images
	"r")  rotate 90 ;;
	# rotate anti-clockwise all images
	"R")  rotate 270 ;;
	# copy to new location
	"c")
		oldfile=$(head -1 | cat -)
		mimetype=$(file --mime-type "$oldfile" | cut -d' ' -f2)
		newfile=$(prompt "Copy ($mimetype) to:" -it "$oldfile")

		if [ "$newfile" ]; then
			[ -d "${newfile%/*}" ] || mkdir -p "${newfile%/*}"
			cp "$oldfile" "$newfile"
		fi ;;
esac

