#!/bin/sh

# Example for $XDG_CONFIG_HOME/sxiv/exec/key-handler
# Called by sxiv(1) after the external prefix key (C-x by default) is pressed.
# The next key combo is passed as its first argument. Passed via stdin are the
# images to act upon, one path per line: all marked images, if in thumbnail
# mode and at least one image has been marked, otherwise the current image.
# sxiv(1) blocks until this script terminates. It then checks which images
# have been modified and reloads them.

# The key combo argument has the following form: "[C-][M-][S-]KEY",
# where C/M/S indicate Ctrl/Meta(Alt)/Shift modifier states and KEY is the X
# keysym as listed in /usr/include/X11/keysymdef.h without the "XK_" prefix.

rotate() {
	degree="$1"
	tr '\n' '\0' | xargs -0 realpath | sort | uniq | while read file; do
        # use imagemagick
        convert "$file" -rotate $degree "$file"
	done
}

case "$1" in
# copy list of paths
"C-x")  xclip -in -selection clipboard ;;
# copy first image to clipboard
"C-c")  head -1 | xclip -selection clipboard -target image/png "$(cat -)" ;;
# set as wallpaper
"C-s")  head -1 | ln -fs "$(pwd)/$(cat -)" ~/.wallpaper  && feh --bg-fill "$HOME/.wallpaper";;
# rotate clockwise all images
"C-r")  rotate 90 ;;
# rotate anti-clockwise all images
"C-R")  rotate 270 ;;
esac

