# Default music directory
# music_directory "/path/to/music/folder"
follow_outside_symlinks "yes"

# create playlist_directory to enable playlists
playlist_directory  "~/.local/share/mpd/playlists"

# these are created automatically
db_file     "~/.local/share/mpd/database"
log_file    "~/.local/share/mpd/log"
state_file  "~/.local/share/mpd/state"

bind_to_address "~/.local/share/mpd/socket"

# for sound
audio_output {
  type  "pulse"
  name  "Pulse Audio"
}
 
# for visualizers
audio_output {
  type    "fifo"
  name    "visualizer_feed"
  path    "~/.cache/mpd.fifo"
  format  "44100:16:2"
}
 
