Section "InputClass"
    Identifier "touchpad"
    Driver "libinput"
    MatchIsTouchpad "on"
    # enable touch on tap
    Option "Tapping" "on"
    Option "TappingButtonMap" "lmr" 
    # enable natural scrolling
    #Option "NaturalScrolling" "true"
    # scroll with edge of touchpad
    #Option "ScrollMethod" "edge"
EndSection
