Section "InputClass"
    Identifier "touchpad"
    Driver "libinput"
    MatchIsTouchpad "on"
    # enable touch on tap
    Option "Tapping" "on"
    # single-finger tap : left clock
    # double-finger tap : middle click
    # triple-finger tap : right click
    Option "TappingButtonMap" "lmr" 
    # enable natural scrolling
    Option "VertScrollDelta" "-120"
    Option "HorizScrollDelta" "-120"
EndSection
