#!/bin/sh

nth() {
    local _n=$1
    tail -n+$_n | head -n1
}

errcho() {
    local _e=0
    [ "$1" = "-e" ] && _e=1 && shift

    2>&1 echo "$*"
    
    [ "$_e" = 1 ] && exit 1
}

# some charging icons are missing, refer to 
# https://github.com/ryanoasis/nerd-fonts/issues/279
# not charging (00 - 10)
# charging     (11 - 21)
_batdir=/sys/class/power_supply/BAT0
[ -d "$_batdir" ] || errcho -e "No battery folder at $_batdir"

_icons=" \n \n \n \n \n \n \n \n \n \n\n\
 \n \n \n \n \n \n \n \n \n \n "

_bat=$(cat $_batdir/capacity)
_status=$(tr "[:upper:]" "[:lower:]" < $_batdir/status)

_charging=0
[ "$_status" = charging ] && _charging=1

# Relies on echo being able to interpret escape secuences (which is the case
# in dash, but not in bash), Use echo -e instead
_icon=$(echo "$_icons" | nth $((_bat / 10 + 11*_charging + 1)))

# full text
_ft="$_icon $_bat% ($_status)"
# short text
_st="$_icon $_bat%"
# foreground color
#_fg
# background color
#_bg
if [ "$_status" = full ]; then
    _fg="$_cgreen"
elif [ "$_status" = discharging ]; then
    if [ $_bat -gt 30 ]; then
        _ft="$_st"
    elif  [ $_bat -gt 15 ]; then
        _fg="$_cyellow"
    else
        _fg="$_cred"
    fi
fi

echo "$_ft"
echo "$_st"
if [ "$_fg" ]; then
    echo "$_fg"

    [ "$_bg" ] && echo "$_bg"
fi

