#!/bin/sh

_level=$(xbacklight -get)

_icons=(" " " " " " " " " " " ")
_index=
_icon=${_icons[$((_level / 20))]}

# for better alignment
[ $_level -eq 100 ] && echo "$_icon$_level%" || echo "$_icon $_level%"
