#!/bin/sh

nth() {
    local _n="$1"

    tail -n+$_n | head -n1
}

_level=$(xbacklight -get)
_icons=" \n \n \n \n \n "
_icon=$(echo -n "$_icons" | nth $((_level / 20)))

# for better alignment
[ $_level -eq 100 ] && echo "$_icon$_level%" || echo "$_icon $_level%"

