#!/bin/sh

_vol=$(pamixer --get-volume)
_muted=$(pamixer --get-mute)


# set icon based on volume level
if [ "$_muted" = "true" ]; then 
    _icon="婢"
    _ft="$_icon $_vol% (muted)"
    _st="$_icon $_vol%"
    _fg="$_cyellow"
else
    if [ $_vol -gt 66 ]; then 
        _icon="墳"
    elif [ $_vol -gt 33 ]; then 
        _icon="奔"
    else 
        _icon="奄"
    fi

    _ft="$_icon $_vol%"
    _st="$_icon $_vol%"
fi


if [ "$_use_short" = yes ]; then
    echo "$_st"
else
    echo "$_ft"
fi
echo "$_st"
if [ "$_fg" ]; then
    echo "$_fg"

    [ "$_bg" ] && echo "$_bg"
fi

