#!/bin/sh

_vol=$(pamixer --get-volume)
_muted=$(pamixer --get-mute)
_warning_color="#ffdc00"

# set icon based on volume level
if [ "$_muted" = "true" ]; then 
    _icon="婢"
    echo "$_icon $_vol% (muted)"
    echo "$_icon $_vol%"
    echo $_warning_color
else
    if [ $_vol -gt 66 ]; then 
        _icon="墳"
    elif [ $_vol -gt 33 ]; then 
        _icon="奔"
    else 
        _icon="奄"
    fi

    echo "$_icon $_vol%"
    echo "$_icon $_vol%"
fi

