#!/bin/sh

# more about %- notation at https://github.com/chubin/wttr.in
_format="%l:%C:%t"

# <short_location>:<long_location>
IFS=: read -r _locs _locl < scripts/weather.data

# try to ping host repeatedly for 10s until it either reaches it or times out
_reachable=$(timeout 10 scripts/is_reachable.sh "wttr.in" && echo true)

_ft="  wttr.in unreachable"
_st="  wttr.in"
_fg="$_cyellow"

if [ $_reachable ]; then
    _weather=$(curl -s "wttr.in/$_locl?format=$_format")
    _weather_cond=$(echo "$_weather" | cut -d':' -f2 | tr "[:upper:]" "[:lower:]")
    _temp=${_weather##*:}

    case "$_weather_cond" in
        sunny)           _icon=" " ;;
        fog)             _icon=" " ;;
        thunderyshowers) _icon=" " ;;
        clear)           _icon=" " ;;
        overcast)        _icon=" " ;;
        *cloudy)         _icon=" " ;;
        *showers)        _icon=" " ;;
        *sleet)          _icon=" " ;;
        *snow)           _icon=" " ;;
        *rain)           _icon=" " ;;
    esac

    _ft="$_locl: $_weather_cond ($_temp)"
    _st="$_locs: $_icon ($_temp)"
    _fg=
fi

if [ "$_use_short" = yes ]; then
    echo "$_st"
else
    echo "$_ft"
fi
echo "$_st"
if [ "$_fg" ]; then
    echo "$_fg"

    [ "$_bg" ] && echo "$_bg"
fi

