# vi: syntax=tmux
set -g default-terminal "tmux-256color"
set -g prefix C-a
set -g status-keys vi
set -g mode-style bg=black
set -g automatic-rename on
set -g focus-events on

set -sg escape-time 10

setenv -g TERM "tmux-256color"

unbind C-b
unbind l
unbind %
unbind \"
unbind up
unbind down
unbind left
unbind right
unbind C-up
unbind C-down
unbind C-left
unbind C-right

bind C-a send-prefix

bind -N "swap current pane"          b  command-prompt -1 -p "swap pane with:" "swap-pane -d -t %%"
bind -N "swap current window"        B  command-prompt -1 -p "swap window with:" "swap-window -d -t %%"
bind -N "create new session"         C  command-prompt -p "new session:" "new-session -As %%"
bind -N "copy buffer to clipboard"   y  run-shell "select-tmux-buffer.sh | xclip -sel clip >/dev/null" \; display-message "Copied tmux buffer to system clipboard"

bind -N "select pane left"    h    select-pane -L
bind -N "select pane below"   j    select-pane -D
bind -N "select pane above"   k    select-pane -U
bind -N "select pane right"   l    select-pane -R
bind -rN "resize pane left"   C-k  resize-pane -U 2
bind -rN "resize pane down"   C-j  resize-pane -D 2
bind -rN "resize pane up"     C-h  resize-pane -L 2
bind -rN "resize pane right"  C-l  resize-pane -R 2

bind -N "switch to last window"           tab  last-window
bind -N "kill current pane (no prompt)"   X    kill-pane
bind -N "reload config"                   r    source-file $XDG_CONFIG_HOME/tmux/tmux.conf


bind -N "vertical split"    |  split-window -h
bind -N "horizontal split"  -  split-window -v

# status bar theme

set -g status on
set -g status-position top
set -g status-justify centre
set -g status-left-length 200
set -g status-right-length 200
set -g status-style fg=white,bg=black

set -g message-style fg=yellow,bg=black
set -g message-command-style fg=yellow,bg=black

set -g pane-border-style fg=white
set -g pane-active-border-style fg=yellow

set -g window-status-style fg=magenta,bg=black
set -g window-status-activity-style bg=magenta,fg=black
set -g window-status-bell-style bg=magenta,fg=black
set -g window-status-separator ' | '

set -g status-right '#[fg=green,bold]#(whoami)#[fg=white]@#[fg=blue]#H '
set -g status-left '#[fg=red,bold][#S] '

set -g window-status-format ' #I:[ #W ] #F '
set -g window-status-current-format ' #[bold]#I:[ #W ] #F '



# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

run $XDG_CONFIG_HOME/tmux/plugins/tpm/tpm
