theme = "kanagawa"

[editor]
scrolloff =  3
line-number = "relative"
cursorline = true
rulers = [80]
color-modes = true

[editor.statusline]
mode.normal = "N"
mode.insert = "I"
mode.select = "S"

[editor.cursor-shape]
insert = "bar"

[editor.indent-guides]
render = true
character = "┊"
skip-levels = 1

[keys.normal]
A-k = "move_line_up"
A-j = "move_line_down"

[keys.insert]
j = { k = "normal_mode" }
