[General]
frontend=widgetsboxmodel
hotkey=Ctrl+Space
memoryDecay=0.6
showTray=false
telemetry=false
terminal=Alacritty

[albert]
global_handler_enabled=false
trigger_enabled=true

[applications]
enabled=true
global_handler_enabled=true
trigger="apps "
use_exec=true
use_generic_name=false
use_keywords=true

[applications_xdg]
enabled=true
use_exec=true
use_keywords=true

[arch_wiki]
enabled=false
trigger="arch "

[aur]
enabled=false

[bookmarks]
enabled=true
global_handler_enabled=true
trigger="bm "

[calculator_muparser]
enabled=false

[calculator_qalculate]
angle_unit=1
enabled=true
global_handler_enabled=false
trigger_handler_enabled=true

[copyq]
enabled=false

[cuis]
enabled=true
global_handler_enabled=true

[docs]
enabled=true

[emoji]
enabled=true
global_handler_enabled=false
trigger_handler_enabled=true

[files]
enabled=true
global_handler_enabled=true
home\jt\documents\followSymlinks=false
home\jt\documents\indexhidden=false
home\jt\documents\maxDepth=255
home\jt\documents\mimeFilters=inode/directory, application/*
home\jt\documents\nameFilters=@Invalid()
home\jt\documents\scanInterval=0
home\jt\documents\useFileSystemWatches=false
home\jt\downloads\followSymlinks=false
home\jt\downloads\indexhidden=false
home\jt\downloads\maxDepth=255
home\jt\downloads\mimeFilters=@Invalid()
home\jt\downloads\nameFilters=@Invalid()
home\jt\downloads\scanInterval=0
home\jt\downloads\useFileSystemWatches=false
home\jt\music\followSymlinks=false
home\jt\music\indexhidden=false
home\jt\music\maxDepth=255
home\jt\music\mimeFilters=audio/*
home\jt\music\nameFilters=@Invalid()
home\jt\music\scanInterval=0
home\jt\music\useFileSystemWatches=false
home\jt\pictures\followSymlinks=false
home\jt\pictures\indexhidden=false
home\jt\pictures\maxDepth=255
home\jt\pictures\mimeFilters=image/*
home\jt\pictures\nameFilters=@Invalid()
home\jt\pictures\scanInterval=0
home\jt\pictures\useFileSystemWatches=false
paths=/home/jt/documents, /home/jt/downloads, /home/jt/pictures

[googletrans]
enabled=false

[jetbrains_projects]
enabled=true

[kill]
enabled=true

[pass]
enabled=true
trigger="pass "

[pluginregistry]
global_handler_enabled=false
trigger="plug "
trigger_handler_enabled=false

[python]
enabled=true
watchSources=false

[python_eval]
enabled=false

[qmlboxmodel]
windowPosition=@Point(332 153)

[ssh]
enabled=true
global_handler_enabled=false
trigger_handler_enabled=true
use_known_hosts=false

[system]
command_lock=light-locker-command -l
command_logout=awesome-client \"awesome.quit()\"
command_poweroff=systemctl poweroff
command_reboot=systemctl reboot
enabled=true
global_handler_enabled=true
logout="notify-send \"Error.\" \"Logout command is not set.\" --icon=system-log-out"
reboot=systemctl reboot
shutdown=systemctl shutdown -h now
title_poweroff=Shutdown
trigger="sys "

[terminal]
enabled=true

[tex_to_unicode]
enabled=false

[timer]
enabled=true

[unit_converter]
enabled=false

[urlhandler]
enabled=true
global_handler_enabled=true
trigger="url "
trigger_enabled=false

[websearch]
enabled=true
fallback_hanlder_enabled=false
global_handler_enabled=true
trigger="web "
trigger_enabled=false
trigger_handler_enabled=false

[widgetsboxmodel]
alwaysOnTop=true
clearOnHide=false
clientShadow=false
displayIcons=true
displayScrollbar=true
followCursor=true
hideOnFocusLoss=true
historySearch=true
itemCount=7
quitOnClose=false
showCentered=true
showFallbacksOnEmpty=true
systemShadow=true
theme=Numix Rounded
trigger_enabled=false
windowPosition=@Point(350 153)

[wikipedia]
enabled=false
trigger_handler_enabled=false

[wikipedia_fb]
fallback_hanlder_enabled=false

[window-switcher]
enabled=false

[youtube]
enabled=false
