[General]
hotkey=Ctrl+Space
last_used_version=0.20.13
memoryDecay=0.6
showTray=true
telemetry=false
terminal=Alacritty

[albert]
trigger_enabled=true

[applications]
enabled=true
trigger="apps "
use_exec=true
use_generic_name=false
use_keywords=true

[arch_wiki]
enabled=true
trigger="arch "

[aur]
enabled=false

[bookmarks]
enabled=true
trigger="b "

[calculator_muparser]
enabled=false

[calculator_qalculate]
angle_unit=1
enabled=true

[cuis]
enabled=true

[emoji]
enabled=true

[files]
enabled=true
home\jt\documents\followSymlinks=false
home\jt\documents\indexhidden=false
home\jt\documents\maxDepth=255
home\jt\documents\mimeFilters=inode/directory, application/*
home\jt\documents\nameFilters=@Invalid()
home\jt\documents\scanInterval=0
home\jt\documents\useFileSystemWatches=false
home\jt\downloads\followSymlinks=false
home\jt\downloads\indexhidden=false
home\jt\downloads\maxDepth=255
home\jt\downloads\mimeFilters=@Invalid()
home\jt\downloads\nameFilters=@Invalid()
home\jt\downloads\scanInterval=0
home\jt\downloads\useFileSystemWatches=false
home\jt\music\followSymlinks=false
home\jt\music\indexhidden=false
home\jt\music\maxDepth=255
home\jt\music\mimeFilters=audio/*
home\jt\music\nameFilters=@Invalid()
home\jt\music\scanInterval=0
home\jt\music\useFileSystemWatches=false
home\jt\pictures\followSymlinks=false
home\jt\pictures\indexhidden=false
home\jt\pictures\maxDepth=255
home\jt\pictures\mimeFilters=image/*
home\jt\pictures\nameFilters=@Invalid()
home\jt\pictures\scanInterval=0
home\jt\pictures\useFileSystemWatches=false
paths=/home/jt/documents, /home/jt/downloads, /home/jt/pictures

[googletrans]
enabled=false

[kill]
enabled=true

[pass]
enabled=true
trigger="pass "

[pluginregistry]
trigger="plug "

[python]
enabled=true
watchSources=false

[ssh]
enabled=true
use_known_hosts=false

[system]
command_poweroff=poweroff
command_reboot=reboot
enabled=true
logout="notify-send \"Error.\" \"Logout command is not set.\" --icon=system-log-out"
reboot=systemctl reboot
shutdown=systemctl shutdown -h now
trigger="sys "

[terminal]
enabled=true

[tex_to_unicode]
enabled=false

[timer]
enabled=true

[unit_converter]
enabled=false

[urlhandler]
enabled=true
trigger="url "
trigger_enabled=false

[websearch]
enabled=true
trigger="web "
trigger_enabled=false

[widgetsboxmodel]
alwaysOnTop=true
clearOnHide=false
clientShadow=true
displayIcons=true
displayScrollbar=false
followCursor=true
hideOnFocusLoss=true
historySearch=true
itemCount=5
quitOnClose=false
showCentered=true
showFallbacksOnEmpty=true
systemShadow=true
theme=Numix Rounded
trigger_enabled=false
windowPosition=@Point(318 153)

[wikipedia]
enabled=true

[window-switcher]
enabled=false

[youtube]
enabled=false
