#!/bin/zsh
# force XDG compliance
alias colorit="colorit --config $XDG_CONFIG_HOME/colorit.conf"
alias gpg="gpg --homedir $HOME/.local/share/gnupg"
alias irssi="irssi --config=$HOME/.config/irssi/config --home=$HOME/.local/share/irssi"
alias luarocks="luarocks --tree $XDG_DATA_HOME/luarocks"
alias mbsync="mbsync -c $XDG_CONFIG_HOME/isync/mbsyncrc"
alias mycli="mycli -l $XDG_DATA_HOME/mycli.log --myclirc $XDG_CONFIG_HOME/myclirc"
alias yarn="yarn --use-yarnrc $XDG_CONFIG_HOME/yarn/config"

# overrides
alias ffmpeg='ffmpeg -hide_banner'
alias fzf='fzf --color=16'
alias grep='grep --color=auto'
alias info="info --vi-keys --init-file $XDG_CONFIG_HOME/info/infokey"
alias ip='ip -color=auto'
alias less='less -FRi'
alias ls='env LC_COLLATE=C ls --group-directories-first --color=auto'
alias mkdir='mkdir -p'
alias vimdiff='nvim -d'

# convinient aliases
alias V='sudo -e'
alias c='xclip'
alias cx='xclip -selection clipboard'
alias la='ls -aa'
alias ll='ls -aalg'
alias mpvoice="mpv --af=lavfi='[ladspa=librnnoise_ladspa:p=noise_suppressor_stereo]'"
alias myip="curl icanhazip.com"
alias sysu='systemctl --user'
alias tt='tmux new -A -s'
alias yv='youtube-viewer'
alias yvn='youtube-viewer -n --autoplay'

if command -v megatools > /dev/null; then
  _megarc="$XDG_CONFIG_HOME/megatools/megarc"
  _tools=(copy df dl export get ls mkdir put reg rm test tools)
  for _megatool in $_tools; do
    alias mega${_megatool}="mega${_megatool} --config=$_megarc"
  done
fi
