# vi:ft=sh

# source .profile since zsh usually sources ~/.zprofile
[ -r "$HOME/.profile" ] && source "$HOME/.profile"

export HISTFILE="$HOME/.local/share/zsh/histfile"
export HISTSIZE=1000
export HIST_IGNORE_DUPS=1
export SAVEHIST=1000
export WORDCHARS=${WORDCHARS/\/}

# zsh-autosuggestions config
ZSH_AUTOSUGGEST_STRATEGY=(history completion)
ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=20
ZSH_AUTOSUGGEST_USE_ASYNC=1
ZSH_AUTOSUGGEST_HISTORY_IGNORE="(cd|ls) *"

if [ "$NVIM" ]; then
    export EDITOR="nvim --server \"$NVIM\" +'set bufhidden=wipe'"
fi
