# vi:ft=sh

# source .profile since normal zsh doesn't source it unless
# it's a login shell
! xset q &>/dev/null && source ~/.profile

export HISTFILE="$HOME/.local/share/zsh/histfile"
export HISTSIZE=1000
export HIST_IGNORE_DUPS=1
export SAVEHIST=1000
export WORDCHARS=${WORDCHARS/\/}

# colorful man-pages
# color codes:
# - black     0
# - red       1
# - green     2
# - yellow    3
# - blue      4
# - magenta   5
# - cyan      6
# - white     7
if [ -t 1 ]; then
	export LESS_TERMCAP_md=$(tput bold; tput setaf 1)
	export LESS_TERMCAP_mb=$(tput bold; tput setaf 7)
	export LESS_TERMCAP_me=$(tput sgr0)
	export LESS_TERMCAP_so=$(tput setab 3; tput setaf 0)
	export LESS_TERMCAP_se=$(tput rmso; tput sgr0)
	export LESS_TERMCAP_us=$(tput smul; tput setaf 4)
	export LESS_TERMCAP_ue=$(tput rmul; tput sgr0)
	export LESS_TERMCAP_mr=$(tput rev)
	export LESS_TERMCAP_mh=$(tput dim)
	export LESS_TERMCAP_ZN=$(tput ssubm)
	export LESS_TERMCAP_ZV=$(tput rsubm)
	export LESS_TERMCAP_ZO=$(tput ssupm)
	export LESS_TERMCAP_ZW=$(tput rsupm)
fi

# zsh-autosuggestions config
ZSH_AUTOSUGGEST_STRATEGY=(history completion)
ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=20
ZSH_AUTOSUGGEST_USE_ASYNC=1
ZSH_AUTOSUGGEST_HISTORY_IGNORE="(cd|ls) *"
