#!/bin/zsh
# cd's to the top of the current git repo
cdgr() {
	_isgit=$(git rev-parse --is-inside-work-tree 2>/dev/null)

	if [ "$_isgit" = true ]; then
		cd $(git rev-parse --show-toplevel)
	else
		2>&1 echo "cdgr: bad working directory: not inside a git repository"
		return 1
	fi
}

# copy arguments to clipboard. useful to copy a path since the arguments
# can be completed using zsh's completion system
yy() {
	while getopts "a" o; do case "$o" in
		# treat arguments as files, and copy absolute paths
		a) _absolute=1 ;;
	esac done
	shift "$(($OPTIND - 1))"

	while [ "$#" -gt 0 ]; do
		arg="$1"

		if [ "$_absolute" = 1 ]; then
			arg="$(realpath -s "$arg")"
		fi

		printf "$arg"

		[ "$#" = 1 ] || printf "\n"
		shift
	done | xclip -selection clipboard
}

# fzf powered man search
fman() {
	[ -z $1 ] && 2>&1 echo "fman what?" && return
	local _line=$(apropos -l $1 | fzf)
	local _name=${_line%% \(*} # cut everything after the manpage name
	[ $_name ] && man $_name
}

# dictionary
def() {
	dict -d gcide "$@" 2>&1 | colorit | less
}

# open my usual programs in tmux
t() {
	session="${1:-home}"
	if tmux has-session -t "$session" 2>/dev/null; then
		if [ -z "$TMUX" ]; then
			tmux attach-session -t "$session"
		else
			>&2 echo "Already inside session [$session]"
		fi
		return
	fi

	tmux new-session -d -s "$session"
	tmux new-window -t "$session"
	tmux new-window -t "$session"
	tmux rename-window -t "$session:0" "mail"
	tmux rename-window -t "$session:1" "music"
	tmux rename-window -t "$session:2" "work"
	tmux send-keys -t "$session:mail" "neomutt" Enter
	tmux send-keys -t "$session:music" "ncmpcpp" Enter
	tmux attach-session -t "$session:work"
}

# edit script: lists file in scriptsfolder using fzf, and opens them in $EDITOR
es() {
	# also search for plain files
	[ "$1" = "-p" ] && opts="-o -type f"

	scriptsfolder="$HOME/.local/scripts"
	# search for executables or symlinks
	script=$(find -L "$scriptsfolder" -type f -a -executable -printf "%f\n" \
	       | fzf --preview "bat -l sh --color always --style plain $scriptsfolder/'{}' ")

	[ -n "$script" ] && nvim "$scriptsfolder/$script"
}

add_to_path() {
	local dir="$1"
	[ -d "$dir" ] && export PATH="$dir:$PATH"
}

# init pyenv modules manually to improve performance
pyenvinit() {
	add_to_path "$PYENV_ROOT/bin"
	add_to_path "$PYENV_ROOT/shims"

	if command -v pyenv >/dev/null; then
		eval "$(pyenv init -)"
		eval "$(pyenv virtualenv-init -)"
	fi
}

# compress a directory into a tar.xz with the same name
# source: https://old.reddit.com/r/archlinux/comments/o2bfha/h265fe2/
txz() {
	tar cf - "$1" | xz -T 0 -zevc > "${1%/}.tar.xz"
}

# shows webcam using special mpv demuxer
campv(){
	local dev="/dev/video${1:-0}"
	if [ -c "$dev" ]; then
		mpv --demuxer-lavf-format=video4linux2 "av://v4l2:$dev"
	else
		>&2 echo "No device found at $dev"
		return 1
	fi
}

v() {
	if [ -n "$NVIM_LISTEN_ADDRESS" ]; then
		nvr -cc split --remote-wait "$@"
	else
		nvim "$@"
	fi
}

trr() {
	env TR_AUTH="$USER:$(rbw get Transmission)" transmission-remote localhost:9091 --authenv "$@"
}

rvminit() {
	# Load RVM into a shell session *as a function*
	[ -s "$RVM_HOME/scripts/rvm" ] && source "$RVM_HOME/scripts/rvm"
}
