# zsh history
setopt appendhistory

# z to jump between directories (with zoxide)
if command -v zoxide >/dev/null; then
  eval "$(zoxide init zsh)"
fi

if command -v starship >/dev/null; then
    eval "$(starship init zsh)"
fi

# run when zsh vi mode is changed shows different indicators for each mode
zle-keymap-select() {
  case $KEYMAP in
  vicmd) echo -ne "\e[2 q" ;;        # block cursor
  viins | main) echo -ne "\e[6 q" ;; # pipe cursor
  esac
}

# default to insert mode
zle-line-init() {
  zle -K viins
  echo -ne "\e[6 q"
}

zle -N zle-keymap-select
zle -N zle-line-init


# ==== ZIM ==== {{{
zstyle ':zim:zmodule' use 'degit'
zstyle ':zim' disable-version-check yes

ZIM_HOME=${XDG_CACHE_HOME}/zim

# Download zimfw plugin manager if missing.
if [[ ! -e ${ZIM_HOME}/zimfw.zsh ]]; then
  curl -fsSL --create-dirs -o ${ZIM_HOME}/zimfw.zsh \
      https://github.com/zimfw/zimfw/releases/latest/download/zimfw.zsh
fi

# Install missing modules, and update ${ZIM_HOME}/init.zsh if missing or outdated.
if [[ ! ${ZIM_HOME}/init.zsh -nt ${ZDOTDIR:-${HOME}}/.zimrc ]]; then
  source ${ZIM_HOME}/zimfw.zsh init -q
fi

source ${ZIM_HOME}/init.zsh
# }}}

# for aliases
[ -f "$ZDOTDIR/aliases" ] && source "$ZDOTDIR/aliases"

# for functions
[ -f "$ZDOTDIR/functions" ] && source "$ZDOTDIR/functions"

# for key bindings
[ -f "$ZDOTDIR/keybinds" ] && source "$ZDOTDIR/keybinds"
