# zsh history
setopt appendhistory

# enable ./ ../ completion
zstyle ':completion:*' special-dirs true
zstyle ':completion:*' completer _expand _complete

# find new executables in PATH after installation
zstyle ':completion:*' rehash true
eval $(dircolors)
zstyle ':completion:*' list-colors $LS_COLORS

# awesome completion
autoload -Uz compinit
zle -N compinit
compinit

# z to jump between directories (with zoxide)
if command -v zoxide >/dev/null; then
  eval "$(zoxide init zsh)"
fi

if command -v starship >/dev/null; then
    eval "$(starship init zsh)"
fi

# run when zsh vi mode is changed shows different indicators for each mode
zle-keymap-select() {
  case $KEYMAP in
  vicmd) echo -ne "\e[2 q" ;;        # block cursor
  viins | main) echo -ne "\e[6 q" ;; # pipe cursor
  esac
}

# default to insert mode
zle-line-init() {
  zle -K viins
  echo -ne "\e[6 q"
}

zle -N zle-keymap-select
zle -N zle-line-init

# ==== Zap ==== {{{
zapf="$XDG_DATA_HOME/zap/zap.zsh"
[ -f "$zapf" ] && source "$zapf"

plug "zsh-users/zsh-autosuggestions"
plug "zdharma-continuum/fast-syntax-highlighting"
# }}}

# for aliases
[ -f "$ZDOTDIR/aliases" ] && source "$ZDOTDIR/aliases"

# for functions
[ -f "$ZDOTDIR/functions" ] && source "$ZDOTDIR/functions"

# for key bindings
[ -f "$ZDOTDIR/keybinds" ] && source "$ZDOTDIR/keybinds"
