# no X server => we're probably sshing
if ! xset q &>/dev/null; then
  source ~/.profile
fi

# shut up
unsetopt beep
# for gitbranch on prompt
setopt prompt_subst
# zsh history
setopt appendhistory

# enable ./ ../ completion
zstyle ':completion:*' special-dirs true
zstyle ':completion:*' completer _expand _complete
# find new executables in PATH after installation
zstyle ':completion:*' rehash true
eval $(dircolors)
zstyle ':completion:*' list-colors $LS_COLORS

# awesome completion
autoload -Uz compinit
zle -N compinit
compinit

# edit command in vim
autoload -z edit-command-line
zle -N edit-command-line

# run when zsh vi mode is changed shows different indicators for each mode
zle-keymap-select() {
  case $KEYMAP in
  vicmd) echo -ne "\e[2 q" ;;        # block cursor
  viins | main) echo -ne "\e[6 q" ;; # pipe cursor
  esac
}
zle -N zle-keymap-select

# default to insert mode on start
zle-line-init() {
  zle -K viins
  echo -ne "\e[6 q"
}
zle -N zle-line-init

# z to jump between directories (with zoxide)
if command -v zoxide >/dev/null; then
  eval "$(zoxide init zsh)"
fi

# for aliases
[ -f "$ZDOTDIR/aliases" ] && source "$ZDOTDIR/aliases"

# for functions
[ -f "$ZDOTDIR/functions" ] && source "$ZDOTDIR/functions"

# for key bindings
[ -f "$ZDOTDIR/keybinds" ] && source "$ZDOTDIR/keybinds"

plugdir="/usr/share/zsh/plugins"
plugins=("zsh-autosuggestions" "fast-syntax-highlighting")

for p in $plugins; do
  [ -f "$plugdir/$p/$p.plugin.zsh" ] && source "$plugdir/$p/$p.plugin.zsh"
done
