#!/bin/sh
# fzf chooser for irc hosts to connect with catgirl

hostsfolder="${XDG_DATA_HOME:-$HOME/.local/share}/catgirl"
user="deskpc"
host=$(find "$hostsfolder" -type s -printf "%f\n" | fzf)

[ -n "$host" ] && exec catgirl -h $host -t localhost.crt -u $user -O url-opener.sh -s $host
