#!/bin/sh
# connects to configured hosts with catgirl

cgfolder="${XDG_CONFIG_HOME:-$HOME/.config}/catgirl/hosts"
conf=$(find "$cgfolder" -type f -printf "%f\n" | fzf)

[ -n "$conf" ] && exec catgirl "hosts/$conf" -s ${conf%.conf}
