#!/bin/sh

# dahua servers folder
_dahuaf="$HOME/.config/ddahua"

errcho() {
	if [ -t 0 ]; then
		>&2 echo "$*"
	else
		notify-send -u low "dmount" "$*"
	fi

	exit 1
}

_fifo="${XDG_CACHE_HOME:-$HOME/.cache}/ddahua.fifo"

if ! command -v mpv >/dev/null; then
	errcho "mpv not found"
elif [ ! -d "$_dahuaf" ]; then
	errcho "No dahua servers folder found at $_dahuaf"
elif [ $(ls -1 "$_dahuaf" | wc -l) -eq 0 ]; then
	errcho "No dahua servers found in $_dahuaf"
fi

_dahua="$(ls -1 "$_dahuaf" | dmenu -i -p "Choose a server")"

# check if selected connection exists
if [ -z "$_dahua" ]; then
	exit 0;
elif [ ! -f "$_dahuaf/$_dahua" ]; then
	errcho "No dahua server with name \"$_dahua\" found"
fi

mkfifo "$_fifo"
trim-conf "$_dahuaf/$_dahua" > "$_fifo" &

while IFS='=' read -r prop value; do
	case "$prop" in
		host)
			_host=$value ;;
		port)
			_port=$value ;;
		user|username)
			_user=$value ;;
		pass|password)
			_pass=$value ;;
		channels)
			_channels=$value ;;
	esac
done < "$_fifo"
rm $_fifo

_channelname=$(echo $_channels | tr ";" "\n" | cut -d: -f1 | dmenu -i -p "Choose a channel:")
_channel=$(echo $_channels | tr ";" "\n" | grep -F "$_channelname" | cut -d: -f2)

exec mpv --no-terminal --title="Camera: $_channelname" "rtsp://${_user:-admin}:${_pass:-admin}@$_host:${_port:-554}/cam/realmonitor?channel=$_channel&subtype=0"
