#!/bin/sh

# mounts folder
_mountf="$HOME/.config/dmount"

errcho() {
	if [ -t 0 ]; then
		>&2 echo "$*"
	else
		notify-send -u low "dmount" "$*"
	fi

	exit 1
}

_fifo="$HOME/.cache/dmount.fifo"

if ! command -v mount.cifs >/dev/null; then
	errcho "mount.cifs not found, install cifs-utils"
elif [ ! -d "$_mountf" ]; then
	errcho "No mount folder found at $_mountf"
elif [ $(ls -1 "$_mountf" | wc -l) -eq 0 ]; then
	errcho "No mounts found in $_mountf"
fi

_mount="$(ls -1 "$_mountf" | dmenu -i -p "Choose a mount")"

# check if selected connection exists
if [ -z "$_mount" ]; then
	exit 0;
elif [ ! -f "$_mountf/$_mount" ]; then
	errcho "No mount with name \"$_mount\" found"
fi

mkfifo "$_fifo"
trim-conf "$_mountf/$_mount" > "$_fifo" &

while IFS='=' read -r prop value; do
	case "$prop" in
		type)
			_type=$value ;;
		target)
			_target=$value ;;
		mountpoint)
			_mountpoint=$value ;;
		options)
			_opts=$value ;;
	esac
done < "$_fifo"
rm $_fifo

[ -d "$_mountpoint" ] || mkdir -p "$_mountpoint"

# add more cases for new mount types
case "$_type" in
	cifs)
		SUDO_ASKPASS=/usr/local/bin/dsudopass sudo -A mount.cifs $_opts "$_target" "$_mountpoint" ;;
esac
