#!/bin/sh
# quick dmenu duckduckgo search

# number of lines to show of history: 0 to disable
_histlines=3
_histfile="$HOME/.cache/ddgo.hist"
_prompt="DuckDuckGo:"

preppend() {
    text="$1"
    file="$2"

    echo "$text" | cat - "$file" > "$file@" && mv "$file@" "$file"
}

cleanhist() {
    sort "$_histfile" | uniq > "$_histfile@"
    mv "$_histfile@" "$_histfile"
}

if [ $_histlines -ne 0 ]; then
    # create if not available
    [ -f "$_histfile" ] || touch $_histfile

    _search=$(dmenu -l $_histlines -p "$_prompt" < $_histfile)
else
    _search=$(echo -n | dmenu -p "$_prompt")
fi

if [ "$_search" ]; then
    # prevents repeated consecutive searches to appear multiple times in
    # history
    if ! (head -n1 "$_histfile" | grep -q "$_search"); then
        preppend "$_search" "$_histfile"
    fi

    [ $(wc -l "$_histfile") -gt 100 ] && cleanhist

    # use xdg-settings to set prefered default browser
    xdg-open "https://duckduckgo.com/?q=$_search"
fi
