#!/usr/bin/env bash

# rdesktop connection launcher with dmenu

# NOTE: For this to work, you either need the dmenu 
# [password patch](https://tools.suckless.org/dmenu/patches/password/)
# is needed, or just store the plain text password in the connection file.

# The script looks for files in $XDG_CONFIG_HOME/dmrdp/connections folder
# and prompts the user to select one. Each connection file is simply a 
# list of arguments to pass to rdesktop. If no /p: (password) argument
# is found, the user is prompted by using dmenu's -P option for password

errcho() {
    1>&2 echo $@
    exit 1
}

if ! command -v rdesktop > /dev/null; then 
    errcho "rdesktop was not found."
fi

connfolder="$HOME/.config/dmrdp/connections"
[ -d "$connfolder" ] || errcho "No connections folder found at $connfolder"

conn=$(ls -1 "$connfolder" | dmenu -i -p "Choose a connection: ")
[ -n "$conn" ] || errcho "No connection selected"

source "$connfolder/$conn"

endpoint="$host${port:+:$port}"

# -K: don't override i3 keybindings
# -k es-ar: use this keyboard layout
options="-K -k es"

rdesktop $options "$endpoint" -u "$user" -d "$domain"

