#!/bin/sh

# xfreerdp connection launcher with dmenu

# NOTE: For this to work, you either need the dmenu 
# [password patch](https://tools.suckless.org/dmenu/patches/password/)
# is needed, or just store the plain text password in the connection file.

# The script looks for files in $XDG_CONFIG_HOME/dmrdp/connections folder
# and prompts the user to select one. Each connection file is simply a 
# list of arguments to pass to xfreerdp. If no /p: (password) argument
# is found, the user is prompted by using dmenu's -P option for password

if ! command -v xfreerdp > /dev/null; then 
    errcho "freerdp was not found."
fi

_connf="$HOME/.config/dmrdp/connections"
[ -d "$_connf" ] || errcho "No connections folder found at $_connf"

# check if connections folder is empty
[ $(ls -1 "$_connf" | wc -l) -eq 0 ]  && errcho "No connections found in $_connf"

_conn=$(ls -1 "$_connf" | dmenu -i -p "Choose a connection: ")
[ -n "$_conn" ] || errcho "No connection selected"

while IFS='=' read -r prop value; do
    case "$prop" in
        user|username)
            _user=$value ;;
        pass|password)
            _pass=$value ;;
        domain)
            _domain=$value ;;
        host)
            _host=$value ;;
        port)
            _port=$value ;;
    esac
done < trimconf "$_conn"

_endpoint="$_host${_port:+:$_port}"

# -grab-keyboard: DON'T grab keyboard
# /dynamic-resolution: update resolution on window resize
_options="-grab-keyboard /dynamic-resolution"

# ask for password if not in config file
_pass=${_pass:-$(dmenu -p "Password for $_user${_domain:+@$_domain}" -P)}

xfreerdp $_options "/v:$_endpoint" "/u:$_user" "/d:$_domain" "/p:$_pass"

